--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Muqsit/ChunkGenerator
build-by-default: true
branches:
- master
projects:
  ChunkGenerator:
    path: ""
    libs:
      - src: SOF3/await-generator/await-generator
        version: ^3.6.1
...
