name: ChunkGenerator
main: muqsit\chunkgenerator\Loader
api: 5.0.0
version: 0.0.3
commands:
  cgen:
    usage: /cgen <world> <minchunkx> <minchunkz> <maxchunkx> <maxchunkz>
    permission: chunkgenerator.command
permissions:
  chunkgenerator.command:
    default: op